### ISSUE TITLE
How to use loop to keep the notification going until user clicked on it? (iOS)

### ISSUE THREAD

**Issue by kerryf88** [vasani-arpit/cordova-plugin-local-notifications#2]
Hi there, I was just wondering if you know how to loop the notification sound until user clicked open the notification for iOS? I realize this is for android but couldn't find any related info for iOS. I'm using katzer's original plugin but at the moment the notification only goes for 30 seconds without repeating.

**Comment by vasani-arpit** [comment]
Hello,
What you want to achieve is not quite possible in iOS. iOS doesn't allow notification repeating more than 30 second.

for this feature you might need something like alarm control.
