### ISSUE TITLE
Headsup notification Stops playing audio and video on my App

### ISSUE THREAD

**Issue by ryanjeric** [vasani-arpit/cordova-plugin-local-notifications#4]
How can I remove the Headsup notification feature in this fork?
This feature makes my app audio/video stops when the notification triggered

I'm using IONIC1.
No error logs on android studio just the notification triggered event.

**Comment by vasani-arpit** [comment]
That functionality is implemented [here](https://github.com/vasani-arpit/cordova-plugin-local-notifications/blob/bd621430d5b7608309be7f7a4d5d33aeadb891bf/src/android/notification/Builder.java#L131)

to know more compere Builder.java with original repo

**Comment by ryanjeric** [comment]
Thanks Bro you save my day

**Comment by vasani-arpit** [comment]
Glad I could help.
