### ISSUE TITLE
alternative for "android.app.Notification.FLAG_INSISTENT"

### ISSUE THREAD

**Issue by neilmaledev** [vasani-arpit/cordova-plugin-local-notifications#5]
Is there another way to repeat the notification sound aside from "FLAG_INSISTENT"?

Cause my problem is that I have an audio playing in my app, then when a new notification appears with looping sound, the audio playing in my app stops. 

I tried to remove 
`android.app.Notification.FLAG_INSISTENT`
from line 240 in Notification.java. 
The result was, the audio playing in my app didn't stop but the notification sound plays only once.

So, I want to keep the looping notification sound without affecting the audio playing in my app.

Any HELP is appreciated. TIA.

**Comment by vasani-arpit** [comment]
AFAIK there isn't. They changed bunch of notification stuffs in android Oreo but I don't think this would be included in it.

**Comment by neilmaledev** [comment]
OIC, thanks
